apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: my-app 
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: my-app 
  template: 
    metadata: 
      labels: 
        app: my-app 
    spec: 
      nodeSelector: 
        "beta.kubernetes.io/os": linux 
      containers: 
      - name: my-app 
        image: #FIXME
        ports:
        - containerPort: 8080
          name: my-app
